### PR TITLE
Added a function to obtain the status of the test from the outline of…

### PR DESCRIPTION
**Pull request by kazuhidet**
… the test result 'TestSummaries.plist'

With the previous logic for the retrieve test results, the Xcode plugin tried to analyze the console output under processing of xcodebuild and try to obtain the test result from it, but this method did not work well in a new development environment such as Xcode 10 .
So I change the this mechanism now test result is taken from test result summary "TestSummaries.plist" output by xcodebuild.

### CODE REVIEW

**Comment by akanksharma** [comment]
Hello,

Is this issue fixed?
Because I am still getting the same error while running my XCUITests with plugin version 2.0.11

Thanks in advance.

**Comment by kazuhidet** [comment]
@akanksharma By default, the newly added function is off, and in that state it behaves like the previous version.
In order to enable the analysis logic of the newly added test result, it is necessary to set the directory to output the test result in "ResultBundlePath" at "Configure".

**Comment by kazuhidet** [comment]
If it still does not fix the problem, try running xcodebuild manualy (with the same parameters as when Plugin runs) and if you provide the console output to me. I will be explore the problem and try to fix it.

**Comment by akanksharma** [comment]
@kazuhidet , 
ResultBundlePath solved the issue.
Thanks again.

**Pull request merged**
