### PR TITLE
Allow setting a custom timeout when unlocking the keychain

### PR DESCRIPTION
**Pull request by Sauraus**
https://issues.jenkins-ci.org/browse/JENKINS-17184

### CODE REVIEW

**Comment by BluMist** [comment]
Any update on this?

**Comment by Sauraus** [comment]
I am keeping a fork for the plugin on my Jenkins server, it does what I need without complicating things, if @lacostej wants to make a fancy implementation then by all means.

**Comment by lacostej** [comment]
If I recall, I made some comments on the patch in December. Some of them have not been addressed. E.g. https://github.com/Sauraus/xcode-plugin/commit/d7dfb4befddefa0eec936c02e383aa1b6fa64b60#commitcomment-9023298

**Comment by lacostej** [comment]
And sorry if I don't answer timely. A bit busy ! :)

**Comment by Sauraus** [comment]
@lacostej we all busy :D

Can you perhaps restate exactly what change you would like to see, there is a lot of text and I want to make sure I do the right thing here. ;)

**Comment by lacostej** [comment]
@Sauraus the relevant comments were on @d7dfb4befddefa0eec936c02e383aa1b6fa64b60. In particular the use of list-keychains.

Ideally as I said, I would prefer the whole xcode plugin to not perform the setting of the keychains, but a wrapper around it to do it. It would feel cleaner to my PoV. But I'll take this one in if we make sure we don't break people's environments.

**Comment by Sauraus** [comment]
I've had to come back to this because of this: http://stackoverflow.com/questions/32763288/ios-builds-ipa-creation-no-longer-works-from-the-command-line/32845990#32845990 which is a much bigger problem.

Can we create a feature request of doing keychain unlocking as a wrapper for now?

**Comment by AnneTheAgile** [comment]
Keychain timeouts are a nightmare for me, and I would love this PR to be accepted.
I offer my some humble comments / questions on this PR. 
>  I'll take this one in if we make sure we don't break people's environments.
I do not see how it does. I think it can add nicer doc, if you like.

**Comment by jakepetroules** [comment]
Can someone PLEASE move this forward? The issue has been reported since several years ago now...

**Comment by domdop** [comment]
Ich werde ab  24.06.2016 nicht im B�ro sein. Ich kehre zur�ck am
05.07.2016.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [jenkinsci/xcode-plugin] Allow setting a custom timeout when unlocking
the keychain (#47)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2016 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidc14** [comment]
Hello everyone, I've just ran into this issue. Is there any hope for a resolution?

**Comment by domdop** [comment]
Ich werde ab  12.12.2016 nicht im B�ro sein. Ich kehre zur�ck am
14.12.2016.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [jenkinsci/xcode-plugin] Allow setting a custom timeout when unlocking
the keychain (#47)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2016 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Pull request closed without merging**
