### PR TITLE
Added jenkins pipeline support by implementing SimpleBuildStep

### PR DESCRIPTION
**Pull request by jnikolai**
Hello :)

I added pipeline support for this plugin, and would like to contribute this back to the mainline.  It was a fairly straightforward change -- but please let me know if you see any issues with it.

### CODE REVIEW

**Comment by saiimons** [comment]
Would love to see this in a release soon :)

**Comment by raniejade** [comment]
Any updates?

**Comment by saiimons** [comment]
@aheritier could maybe give his feedback ;)

**Comment by Brantone** [comment]
Sorry, I've been removed from Jenkins + Xcode for a bit.
I don't supposes tests are feasible for these changes?

**Comment by raniejade** [comment]
Bumping it up again :)

**Comment by Brantone** [comment]
Would still like to see some tests (my availability to focus on Jenkins+Xcode has been limiting, but expect to pick up fairly soon) ; ...  however, if everyone's cool with it, I'll try to get it merged + released tonight.

**Comment by raniejade** [comment]
Any news?

**Comment by rendion** [comment]
This swallows all exception from the perform method when it returns false.

**Pull request merged**
