### PR TITLE
Fix for FATAL: Log statements out of sync

### PR DESCRIPTION
**Pull request by bgalamb**
Don't die if there is a success message in the log. Try to find fallback possibilities to categorise the test. (You cannot influence anyhow the order of lines in the xcode log)

### CODE REVIEW

**Comment by kazuhidet** [comment]
I 'm testing your fixes to merge your PR.
If possible, would you please report in a bit more detail how you found this problem?
When I tried it seems to work correctly in the case reported in 'FATAL: Log statements out of sync' in the past.

**Comment by bgalamb** [comment]
@kazuhidet 
The problem is well described here:

https://issues.jenkins-ci.org/browse/JENKINS-37072?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20xcode-plugin%20AND%20text%20~%20%22log%20statement%20out%20of%20sync%22

The root cause of the problem seems to be that there might be cases when asynchronous log entries appear in the log of xcode, which dont necessarily follow the given mandatory order of the plugin,. These produce the xcode plugin to exit with fatal exception, and thus terminate it.

If so the number of test, successful tests, passed tests is not accurate and unpredictable. It can be observed by simply looking at the test trends graph. There can be high peaks and valleys in the number of tests despite it is the same number as before.

The fix is to make sure that the plugin does not terminate (and produce weird test result graphs) if there is an error in the order of the logs. We are able to gather the information required from other places/variables too.

The fix is to enhance the parsing of the output as fail safe as possible and don't terminate too early, specially if there is a successful test log entry (It is true that it was not in sync with the start "tag" of the test, but don't exit in this case.)

**Comment by kazuhidet** [comment]
@bgalamb Thanks for the reply.
I understood the phenomenon you pointed out.
Analysis of the output of xcodebuild with XCodeBuildOutputParser may have various difficult problems.
In the latest Xcode 9, it became possible to use the operate the UI test in parallel, etc. When using this function etc, it will not operate as expected.
I will test a little more assuming various cases and think whether there is something good solution.

**Comment by kazuhidet** [comment]
Perhaps the cause of this problem is the buffering problem mentioned in the next report?

https://stackoverflow.com/questions/18995187/xcodebuild-corrupts-test-result-output-when-output-redirected-to-file

If so, it seems to be good to inject NSUnbufferedIO=YES, as in this report, before running xcodebuild.

**Comment by kazuhidet** [comment]
@bgalamb Based on your advice, I modified the XCodeBuildOutputPerser and tried submitting a new PR #95 
Perhaps, I think this will work quite well.

**Pull request merged**
