### PR TITLE
Import lampietti's Xcode9 modification to 2.0.0 and fix little bit.

### PR DESCRIPTION
**Pull request by kazuhidet**
Merge Lucas Lampietti's PR#86(add xcode9 new signing support [JENKINS-45509]) in to Latest Version 2.0.0 and will fix problem when select Team from plludown.

### CODE REVIEW

**Comment by wsoula** [comment]
When will this be merged?  We have been using this PR build for a few weeks now and it works great for us.

**Comment by kazuhidet** [comment]
I am sorry, I do not know when it will be done.
Maintainer of this plugin seems to be busy recently, it seems that various proposals are left behind.

**Comment by mob-sakai** [comment]
Hi, @kazuhidet !
Help me please.

I set it up as follows.
image
image

And the environment variables are as follows.
```
XcTeamId=XXXXXXXXXX
XcExportMethod=enterprise
```

Then, the following error occurred.
```
Error Domain=NSCocoaErrorDomain Code=260 "The file “enterpriseXXXXXXXXXXExportOptions.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=......../enterpriseXXXXXXXXXXExportOptions.plist, NSUnderlyingError=0x7f8682d206c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

The name of the actually generated file is `enterprise $ {XCodeTeamId}ExportOptions.plist`.
image

**Comment by kazuhidet** [comment]
Hello, mob-sakai
It may be helpful to you,

https://github.com/kazuhidet/xcode-plugin/commit/13bbaac89b9f8ad3a0b38e23cee8da0b51836a3a

**Comment by mob-sakai** [comment]
I appreciate your help!

**Comment by duynb92** [comment]
Hi @kazuhidet ,
Can you help me?



And the environment variables are also setup.
But it can not find the variables, it just say {APP_BUNDLE_ID} and {APP_PROVISIONING_PROFILE_UUID}.

Thanks !

**Comment by kazuhidet** [comment]
Hi @duynb92 
I Fix It.

But please think about a bit.
Since Bundle ID and Provisioning UUID can set up this combination in several targets, probably it is not supposed to specify this as an environment variable.

**Comment by duynb92** [comment]
Thanks for your help!

Actually, I want to inject the BundleId and ProvisioningProfile variables when trigger the build, any other ways to achieve this?

I assume the BundleId can be read from the XcodeProject, either ProvisioningProfile, but in my scenario, i may set it wrong, so I want to configure the pipeline to make it right.

**Comment by kazuhidet** [comment]
If the setting 'Development Team' was selected other than 'none (specify one below)' then developmentTeamID is invalid, so add logic for that condition.
It would be nice to be able to describe the logic above with just jerry, but I did not know how to do it, so please let me know if anyone knows it.

**Comment by wenbobao** [comment]
@aheritier When will this be merged?

**Comment by aheritier** [comment]
Hi @wenbobao 

  Did you give a try to the SNAPSHOT?
  As I already said I'm not using this plugin anymore and I'm looking for a new owner (@kazuhidet did an awesome work here). I can always blindly merge and release but ... there is a big risk

**Comment by kazuhidet** [comment]
@aheritier If no one intends to take over the project ownership of this plug-in, I will take over it for the time being.
Because I still use this plugin and I need it.
And, some people will help me with development and testing.

**Comment by aheritier** [comment]
Hi @kazuhidet I'll give you the access with pleasure.
Just follow https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin and request the access on the developers mailing list and you'll be set shortly
Thanks a lot for your help

**Comment by batmat** [comment]
Also, maybe nit-picking, but @kazuhidet you're saying you took https://github.com/jenkinsci/xcode-plugin/pull/86 and fixed things and so on. 

From a licensing/attribution perspective, seems like we're not very clean here. In your commit history, I cannot see @lampietti anywhere. Did you really rewrite everything from scratch?

**Comment by kazuhidet** [comment]
@lampietti @batmat
I was very sorry if it seemed like that.
PR # 87 is not written from scratch. It is based on @lampietti's PR # 86 with some modifications.
Regarding the @lampietti's commit log, it does not remain in the log because we applied the his modification manually. Because I trying to marge his PR to my branch but it failed. so I did it manually.
I wanted to get an environment running on Xcode 9 quickly, so I sent PR in that state.
I will clean my environment and import PR again in step by step, reconfigure the correct branch and then I am planning to submit PR again.

**Comment by kazuhidet** [comment]
I once restored the branch I used for this PR to the initial clean state and then rebuild it by taking other necessary PR step by step.

**Comment by kazuhidet** [comment]
Add function for support multiple versions of Xcode without using 'EnvInject Plugin'.
Because it seems that codeign of xcodebuild has a problem with recently released Xcode 9.3, the archive built with app-store can not be signed with AdHoc provisioning profile for the following error.

Information on Xcode installed in the system can be set with 'Global Tool Configuration'.



You can select the version of Xcode set by 'Global Tool Configuration' by plugin setting.


If you choose the'Default' for Xcode version, plugin will not do anything, so you can switch Xcode using 'EnvInject Plugin' as well.

**Comment by kazuhidet** [comment]
Add function for support multiple versions of Xcode without using 'EnvInject Plugin'.
Because it seems that codeign of xcodebuild has a problem with recently released Xcode 9.3, the archive built with app-store can not be signed with AdHoc provisioning profile for the following error.

"My Application AdHoc" doesn't include the beta-reports-active entitlement., IDEProfileQualificationErrorMissingEntitlements=(
    "beta-reports-active"
)}

Information on Xcode installed in the system can be set with 'Global Tool Configuration'.



You can select the version of Xcode set by 'Global Tool Configuration' by plugin setting.


If you choose the 'System default' for Xcode version, plugin will not do anything, so you can switch Xcode using 'EnvInject Plugin' as well.

**Pull request merged**
