### PR TITLE
This PR fixes JENKINS-32987, it completes PR #68

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
Can you have a look at it @reviewbybees @lacostej  please ?

**Comment by aheritier** [comment]
@patcadelina @joshuaspence can you give a try to this SNAPSHOT please ?
https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/134/org.jenkins-ci.plugins$xcode-plugin/artifact/org.jenkins-ci.plugins/xcode-plugin/1.4.10-SNAPSHOT/xcode-plugin-1.4.10-SNAPSHOT.hpi
If it is ok I'll merge/release it

**Comment by madmunki** [comment]
Can we pull #69 as well? it was a single line of code that changed. I have been using the snapshot for it in our production build machine for awhile with no issues.

**Comment by patcadelina** [comment]
LGTM @aheritier, by all means let's merge. Thanks!

**Comment by daspilker** [comment]
Any progress on this? If this has been released, I will merge https://github.com/jenkinsci/job-dsl-plugin/pull/750.

**Comment by aheritier** [comment]
@daspilker Merged. I will release it in few minutes

**Pull request merged**
