### PR TITLE
Added a function to retrieve information necessary for CodeSign from Xcode project.

### PR DESCRIPTION
**Pull request by kazuhidet**
I have implemented a function to get information on the provisioning profile UUID, Bundle ID etc from the Xcode project file, which is required to do CodeSign.
This is useful when you want to compile existing code without taking time and effort.
(Especially if you do not want to update with automatic your profile or certificate without permission)
If the Xcode project already has information on manual codesign, just check the checkbox.
That's it.

### CODE REVIEW

**Comment by kazuhidet** [comment]
I think that it will work properly, but someone will send a interrupt
 signal to Jenkins CI.

**Comment by paulogodinhoaq** [comment]
O my this will be a huge game changer! I had lots of trouble first setting up this plugin, everything would work fine in XCode but through jenkins it would fail. Auto signing will save a good deal of lives around.

**Comment by kazuhidet** [comment]
OK, everyone can forget about this request.
I tried making it with a little thought but it was convenient.

**Comment by paulogodinhoaq** [comment]
@kazuhidet I meant that the original XCode plugin, without auto signing, is a huge deal. Lots of keychain opening, provisioning and team problems. Your PR will solve a great deal! 

Unfortunately, I couldn't make Auto Signing work, I will post my error later.

**Comment by kazuhidet** [comment]
@paulogodinhoaq When using automatic code sign in Xcode 8 and later, since xcodebuild tries to access Xcode-AlternateDSID and Xcode-Token included in your keychane, it is necessary to give appropriate access permission to these two entries.
Also, "Unlock Keychain?" In the plugin does not seem to work for these items.

Anyway, I will wait for more information from you.

**Comment by paulogodinhoaq** [comment]
@kazuhidet Ok, lets go step by step.

### Automatic Signing

Automatic Signing **DOES WORK**, my problem was that the XCode project was set with manual signing, I had to open the project and tick the Automatic Signing box.

Automatic Signing while archiving and exporting an .IPA does **NOT** work and gives me the following error just after finishing the archive:

`** ARCHIVE SUCCEEDED **

Cleaning up previously generated .ipa files
Cleaning up previously generated .dSYM.zip files
Packaging IPA
ERROR: Build step failed with exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at au.com.rayh.XCodeBuilder._perform(XCodeBuilder.java:996)
	at au.com.rayh.XCodeBuilder.perform(XCodeBuilder.java:394)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Xcode' marked build as failure
Finished: FAILURE`

### Manual Signing

Manual Signing continues to work without a problem for compiling.

When archiving and generating an IPA, the new field to insert a Provisioning Profile UUID is quite confusing. I couldn't find this UUID anywhere, I only got a hold of it because it was logged when trying to build using manual signing, other than that it is a mystery how to get a hold of it.
After providing the UUID, everything worked and I got an .IPA

### Building the plugin 

I pulled this PR using the command line and compiled using Maven, it is necessary to say that I am new to this build tool. Everything went alright with the compilation, but a couple tests failed after the building and it was aborted, what I did was just delete the `test` folder that came with the PR and it compiled with no problems.

If you have anything you want to check or try, I am at your service, I want to help to clear this PR for integration as soon as possible because I really think it will help a great deal.

**Comment by kazuhidet** [comment]
@paulogodinhoaq I will continue to investigate the problem of failing the test when building the plug-in you pointed out in "Building the plugin".
Next, I think that perhaps the recognition of you and me is different. 'Automatic Signing' or 'Manual Signing' in the plug-in does not switch the Code Sign method of the Xcode project. It only to inform the plugin to the state of the current Code Sign method of the Xcode project.
The reason why needed it was that the original plugin did not have the ability to parse Xcode projects and did not have any way to know about it.

Actually, it is possible to switch the code sign method of Xcode project by using a simple shell script etc. together.
If necessary, we will tell you about how to do it after summarizing the information.

**Comment by kazuhidet** [comment]
- First, although it is the original xcode plugin (Ver. 2.0.1), this seemed not to handle the new code sign mechanism of xcode 9 well.

- So I tried PR #86 of 'Lucas Lampietti', which seemed to work very well, at least for automactic signing.
So I modified PR #87 to fix some bugs in this version.

My frustration with this 'Lucas Lampietti' fix is that you had to set a lot of information manually as a plugin if you set the code sign method to 'Manual signing'.
Because many projects that I still need to use 'Manual signing' still existed.
I modified the 'Lucas Lampietti' PR # 86 further to make it possible to reduce manual information setting when I selected 'Manual signing'.
That will be this PR #91.

And unfortunately xcodebuild does not have the ability to override the signing method of xcode project.

**Comment by kazuhidet** [comment]
@paulogodinhoaq For your reference, I will show a shell script to forcibly rewrite information for 'manual signing' included in Xcode Project into information suitable for 'automatic signing'.
It is not impossible to incorporate the equivalent function into the Xcode plugin, but I think that this is not preferable as this method will cause rewriting of the Xcode project.

It was a very dirty code as I quickly wrote it up in a hurry.
Also carefully that Xcode Project will be converted to XML format regardless of input format.

https://github.com/kazuhidet/drop_autosign_info

**Comment by kazuhidet** [comment]
@paulogodinhoaq Oh! really sorry.
Finally I could understand what you wanted to tell and the cause of the problem was found, so I hurried it up now so I will reflect it when that is over.

**Comment by kazuhidet** [comment]
Since I did not use Jenkins' file I / O, So I fixed the problem that loading of Xcode project does not work on remote node.

**Pull request merged**
