### PR TITLE
Export archive

### PR DESCRIPTION
**Pull request by Blahartinger**
Fixing some null pointer exceptions from this fork https://github.com/jenkinsci/xcode-plugin/pull/76 which itself migrates the xcode-plugin to support XCode 8.3.x+.

Also, enterprise shouldn't be the default signing type. Changed this to ad-hoc.

### CODE REVIEW

**Comment by aheritier** [comment]
It seems better @Blahartinger (I did only a code review)
Are there some people interested to test this new SNAPSHOT please ? 
https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/164/org.jenkins-ci.plugins$xcode-plugin/artifact/org.jenkins-ci.plugins/xcode-plugin/1.4.12-SNAPSHOT/xcode-plugin-1.4.12-SNAPSHOT.hpi

**Comment by ToninZhao** [comment]
@Blahartinger I tried "xcode-plugin-1.4.12-SNAPSHOT.hpi", but failed.
FATAL: No global development team or local team ID was configured.

**Comment by Blahartinger** [comment]
@ToninZhao 
That's part of the new plugin changes though. You need to configure that field in jenkins now. Either set a global one, or plop in your team id in the textfield.

**Comment by sivakspt** [comment]
xcodebuild: error: The flag -scheme is required when specifying -archivePath but not -exportArchive.

I am getting this error while creating a build.

**Comment by sivakspt** [comment]
Any update on the above issues?

**Comment by aheritier** [comment]
any idea @Blahartinger ?
Myself I had no time to work on this and I really don't expect to find some time in the next few weeks.
All feedbacks / contributions welcome. As I already said, we'll welcome new active committers with pleasure

**Comment by lucasleelz** [comment]
@Blahartinger  I do not know what team id is, can be described in more detail?

**Comment by lucasleelz** [comment]
@Blahartinger I also found that `Development Team` is not persistent, and if you modify the configuration every time you have to choose `Development Team`.

**Comment by chrisbeall** [comment]
@Blahartinger Snapshot release works fine for me, too, except for the issue with `Development Team` not being persistent.

**Comment by kapfab** [comment]
We used the Snapshot for our latest iOS builds, everything works fine.
We specified a "Development Team ID" for our builds, which seems to be persistent, so we were not affected by the issue related above.

**Comment by Blahartinger** [comment]
@sivakspt - this is how xcodebuild commandline tool is expected to be used. Scheme is required for archivePath and not exportArchive. See the following example from [here](http://subathrathanabalan.com/2016/01/07/building-ipa-export-archive/).

I'll look into Development Team ID not being persistent.

```
# Archive the application
xcodebuild \
-scheme "${SCHEME_NAME}" \
-sdk "${TARGET_SDK}" \
-archivePath "${PROJECT_BUILDDIR}/${SCHEME_NAME}.xcarchive" \
-configuration Release \
PROVISIONING_PROFILE="${PROVISIONING_PROFILE}" \
archive 

# Export the archive to an ipa
xcodebuild \
-exportArchive \
-archivePath "${PROJECT_BUILDDIR}/${SCHEME_NAME}.xcarchive" \
-exportOptionsPlist "${EXPORT_PLIST}" \
-exportPath "${BUILD_OUTPUT_DIR}" 

```

**Comment by Blahartinger** [comment]
Ok, I think I may have fixed it @lucasleelz @chrisbeall

**Comment by Blahartinger** [comment]
@aheritier you should see/review in my last commit what was missing to fix the persistence issue mentioned above.

**Comment by Blahartinger** [comment]
Latest snapshot if you want to try it https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/165/org.jenkins-ci.plugins$xcode-plugin/artifact/org.jenkins-ci.plugins/xcode-plugin/1.4.12-SNAPSHOT/xcode-plugin-1.4.12-SNAPSHOT.hpi

**Comment by aphex3k** [comment]
Whenever I make changes to the configuration in the Jenkins job it forgets about the globally configured dev id selected and resets it to nothing selected... I guess it needs some work still?

Can anyone confirm?

Steps to reproduce:

1. Configure any number of global developer profiles, I configured 2
1. configure a jenkins job using the Xcode plugin with one of the global profiles
1. run the job to confirm it signs the App correctly 
1. configure the job and change something not Xcode-plugin related, like adding an execute shell step
1. run the job again

For me, it fails signing with an error that no global or local developer profile had been selected...

**Comment by alshari86** [comment]
@Blahartinger when will this be merged and released? I need to install the new xcode plugin, right?

**Comment by Blahartinger** [comment]
@alshari86 - not up to me dude. I'm just a community member like yourself that uses the plugin, found it broken, someone else actually made the initial changes for this PR, and I just continued to fix the bugs and previous code review asks. Just moving the needle...I'm not even a regular contributor to this plugin. 

You're able to use the latest snapshot to try out where things are at right now, there's just a persistence issue when using global developer profiles, setting a team id directly seems to work well for me. 

If I get some time soon I'll continue looking into the global dev profile persistence issue but anyone else is also free to try and push this forward.

**Comment by Blahartinger** [comment]
@lampietti - you started these changes originally, any idea on the persistence issue? I've tried to make progress on addressing a few other concerns and small bugs.

**Comment by Blahartinger** [comment]
Ok friends, I think I've nailed the persistence issue for real this time. Try it out for us? 
@aphex3k @lucasleelz @chrisbeall
https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/166/org.jenkins-ci.plugins$xcode-plugin/artifact/org.jenkins-ci.plugins/xcode-plugin/1.4.12-SNAPSHOT/xcode-plugin-1.4.12-SNAPSHOT.hpi

**Comment by aheritier** [comment]
@Blahartinger 

> sorry not up to me dude, I don't have write access to this repository - can't merge it 

We can fix that :)

I had a look at the recent changes you did and they seem to be fine. I didn't test them (it's just a code review) as I don't have anymore the required environment/project

AFH @jenkinsci/code-reviewers 

All feedbacks from real users who can test the SNAPSHOT are welcome. I can blindly merge/release but I would really prefer to have some people feedbacks before.

**Comment by chrisbeall** [comment]
I tested the latest snapshot, and it seems to be working fine. The persistence issue on the develoment team drop-down is fixed. Tested with Xcode 8.3.2.

**Comment by alshari86** [comment]
@chrisbeall I am new on Jenkins, for the snapshot, how do I use it? Do I just copy to the plugin folder of jenkins?

**Comment by chrisbeall** [comment]
@alshari86 Manage Jenkins --> Manage Plugins --> Advanced --> Upload Plugin

**Comment by alshari86** [comment]
@chrisbeall I met three problems totally so far, fixed the first two by providing team ID and Xcode scheme, but for the 3rd one, old Xcode plugin will check dependency and get certificate automatically from my local keychain. Why this one doesn't? Did you see it?
Issue1: FATAL: No global development team or local team ID was configured
Issue2: xcodebuild: error: The flag -scheme is required when specifying -archivePath but not -exportArchive
Issue3: Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "Dealclan LLC" with a private key was found

**Comment by Blahartinger** [comment]
@alshari86 - for #3 it still does that, provided it's set up correctly. I think I may know what your problem is...
There is another new field, Export method,  with a built in assumption that by default is configured for ad-hoc builds. Are you building a development or enterprise signed app? Without changing to the appropriate value the plugin may fail to resolve the correct signing certificate.

Export method ( defaults to ad-hoc)
"The export method of the .app to generate the .ipa file. Should be one in 'development', 'ad-hoc', 'enterprise' or 'app-store'."

**Comment by alshari86** [comment]
@Blahartinger I am building development app, I have developer certificate in my keychain,  but it still shows the error whatever I input in the Export method field. Any settings for the certificate? Will it automatically pick up from keychain?

**Comment by Blahartinger** [comment]
@alshari86 - is your Export field set to development? Is the correct keychain also set?

**Comment by alshari86** [comment]
@Blahartinger any way to contact you only? Very appreciate for your time and guidance and don't want to bother others here ;)

**Comment by Blahartinger** [comment]
You can email me at Bryan.lahartinger@gmail.com and I can try to help you out.

**Comment by alshari86** [comment]
The new plugin works for me right now after fixing above issues :)
Not sure when we will get this merged and get new plugin released? @aheritier

**Comment by alshari86** [comment]
@Blahartinger @aheritier @chrisbeall 
I have one problem here and really need your help on this.
I have one job building for iPhone real device, so package to ipa file and under "ipa-dir/**/*.ipa", in this job the "archive artifacts" works fine and I can see ipa file once job is successful
I have another job building via iphonesimulator sdk which is used to generate ".app" file for simulator running automation. In this job, when I set archive artifacts to "build-dir/**/*.app", it always failed with error "no artifacts found in build-dir/**/*.app",  but when I check my workspace, the .app file as well as the path are both correct. Why it always failed to find this .app file? 
But another job can find .ipa successfully. 
Any one has idea on this? This blocks my automation job right now

**Comment by aphex3k** [comment]
@Blahartinger I can confirm that the issue with persisting the dev team seems to be resolved with this version.

**Comment by lucasleelz** [comment]
Just download the latest code, and packaged xcode plugin, uploaded to jenkins. Restart jenkins, It's OK!.
thanks @Blahartinger

**Comment by aheritier** [comment]
@chrisbeall @aphex3k @lucasleelz seems to be ok for this change thus I propose to merge it. Is there something else to merge before to release cc @Blahartinger ?
We will have to update the wiki and clearly document changes done in this release. 
Due to the addition of the new team parameter which is mandatory we should mark the plugin as incompatible with previous versions ? 
https://wiki.jenkins-ci.org/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions
When you upgrade you have to update your jobs using it
Also it's not clear for me which minimal version of XCode is required now ? In #76 we were talking about version 7 but I'm not sure if with all recent change we don't move the pre-requisite to 8.3 ?

**Comment by Blahartinger** [comment]
@aheritier I think that should be it for this change. Ehats here unblocks xcode 8.3. It's possible that archivepath isn't required in some cases and thus scheme param could be avoided ( though more investigation required). I also think the new params that are required maybe deserve to be top level in the UI rather hen burried in advanced settings but all of these things can be future additional changes.

**Comment by alshari86** [comment]
@aheritier who is going to merge this and release new xcode plugin?

**Comment by aheritier** [comment]
@alshari86 it seems I am the only "active" committer thus I'll do it

**Comment by kapfab** [comment]
Thanks a lot, @Blahartinger and @aheritier!

This PR solves a critical compatibility issue with the latest Xcode and iOS releases. Don't you think this justifies a new release for this plugin (latest is from September 2016) ?

**Comment by aheritier** [comment]
@kapfab yes but before I need at least to 

- bump the version to 2.0.0 and mark it incompatible ( https://wiki.jenkins-ci.org/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions )
- update wiki docs

**Comment by aheritier** [comment]
If you tried this PR please give a try to https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/169/org.jenkins-ci.plugins$xcode-plugin/
It is the latest build from the master branch after it's merge.
It's important to verify that we don't have a regression.

**Comment by kapfab** [comment]
@aheritier, we've just built a few IPAs from your latest Snapshot, everything seems fine.
We could not try all the options, though. As we don't use the Team Name but only the Team Id, we can't tell about the persistence issue.

Just one remark: description and help for the "Xcode Schema File" option still states "Only needed if you want to compile for a specific schema instead of a target", which is not true anymore as it's now required with Xcode "-archivePath" option.
It should now be "Needed if you want to compile for a specific schema instead of a target, or if you want to generate an archive or an IPA".
But I think we all can live without it for the moment.

**Comment by aheritier** [comment]
Fixed @kapfab

**Comment by kapfab** [comment]
Perfect then!

**Comment by aheritier** [comment]
I just pushed all required commits before to release a version 2.0.0
The plugin now requires Java 7, Jenkins LTS 1.625.1 and Xcode 7 minimum (it is mandatory to use it for Xcode >= 8.3)
You can try the last binaries from https://jenkins.ci.cloudbees.com/job/plugins/job/xcode-plugin/171/org.jenkins-ci.plugins$xcode-plugin/
If noone objects I'll update the wiki tomorrow and I'll release it

**Comment by aheritier** [comment]
Released as 2.0.0. Should be in our update center in few hours. Wiki updated : https://wiki.jenkins-ci.org/display/JENKINS/Xcode+Plugin
Thx everyone for your help in maintaining this plugin

**Comment by alshari86** [comment]
Great!

**Comment by rburger** [comment]
Great news!!! :-)

**Comment by 04pmsuu1** [comment]
Looks like xcode plugin always generate archive, independent which value set in "Generate Archive?"

**Comment by lucasleelz** [comment]
Great!!!

**Comment by liuguanlin** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-44550

xcodebuild: error: The flag -scheme is required when specifying -archivePath but not -exportArchive

**Comment by kapfab** [comment]
@liuguanlin Did you specify your Project Scheme in the "Xcode Schema file" option of your existing job(s) ?

**Comment by liuguanlin** [comment]
@kapfab  @alshari86  No, "Xcode Schema file"  need to specify? How to specify？I do not know how to fix this problem

**Comment by ToninZhao** [comment]
@liuguanlin In "Advanced Xcode build options" ==> "Xcode Schema File" step, you should fill your project target in the form.

**Comment by ToninZhao** [comment]
@liuguanlin In "Advanced Xcode build options" ==> "Xcode Schema File" step, you should fill your project scheme in the form.

**Comment by 04pmsuu1** [comment]
Guys, how about https://issues.jenkins-ci.org/browse/JENKINS-44574?

**Comment by kapfab** [comment]
Looks like the same (non-)issue… Archive is generated when an IPA build is requested. And as no Scheme is specified…
Looks like the Scheme option would now need to be unburied from the Advanced options to be more visible. Or an update of the description of the Build IPA option might help.

**Pull request merged**
