### PR TITLE
no xcode build logs in console but separate file

### PR DESCRIPTION
**Pull request by domdop**
possibility to turn off logs from xcodebuild to jenkins console output but to a
separate logfile

### CODE REVIEW

**Comment by domdop** [comment]
@lacostej: could you please merge this pull request?!

**Comment by lacostej** [comment]
Trying to wrap my head around that one again...

If I remember, my concerns were
* why do we have 2 identical close() methods ? Can we remove one ?
* can the try/catch go away if we refactor the code ? 
* minimize the formatting changes to reduce conflicts with other patches

In fact, I wonder if the LineBasedFilterOutputStream shouldn't be refactored as a filter to a given ouptut stream, in our case a composite/tee [http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/output/TeeOutputStream.html or whatever implementation available in jenkins] of
Console (buildListener.getLogger()) and logFileOutputStream.

I.e. something like

    OutputStream streams = null;
    if (consoleLog && logFileOutputStream != null) {
       streams = new Tee(log, logFileOutputStream);
    } else {
      if (consoleLog)
        streams = log;
      if (logFileOutputStream != null)
        streams = logFileOutputStream;
    }
    this.captureOutputStream = new LineBasedFilterOutputStream(streams);

Am I missing something ?

**Comment by domdop** [comment]
it sounds great :+1: 
is something to do for me?

**Comment by lacostej** [comment]
The less I have to do, the happier I am :)
Are you able to implement and try those things out ? I would prefer them tested on a server, before merging them.

**Comment by domdop** [comment]
at the moment it is a bit difficult ... but i will do it as soon as possible ...

**Comment by lacostej** [comment]
completely understood...

**Comment by domdop** [comment]
now i remember why i can't use i.e. a TeeOutputStream ...
because i want to heave the test results in console, even if logging to console is turned off ...

so i only have to remove one close-method, the try/catch and the formating-changes?!

**Comment by lacostej** [comment]
I am missing something. In https://github.com/jenkinsci/xcode-plugin/pull/53#issuecomment-78248073, the Tee is only introduced if consoleLog AND logFileOutputStream is not null. How does that change the behaviour with your implementation ?

**Comment by domdop** [comment]
i can't handle only to log to file with this

the compile-logs should only be logged to file and the test-logs to both (even console-log is turned off)

**Comment by lacostej** [comment]
can we skype ? @lacostej That may make it easier.

**Comment by domdop** [comment]
sorry i am not able to skype at work ...

**Comment by domdop** [comment]
how would LineBasedFilterOutputStream.write(int b) look like?

**Comment by lacostej** [comment]
OK. Let' say you focus on the 2 other issues right now, and I'll look at the third one. I need to look at the code outside of this PR :)

**Comment by domdop** [comment]
i created a new pull request (https://github.com/jenkinsci/xcode-plugin/pull/60) ...

**Comment by aheritier** [comment]
replaced by #60

**Pull request closed without merging**
